googlemaps/react-native-navigation-sdk

- android/src/main/java/com/google/android/react/navsdk/NavModule.java
- ios/react-native-navigation-sdk/NavModule.m
> fix: simulate location

- .github/conventional-commit-lint.yaml
- .github/workflows/release-please.yml
- example/src/App.tsx
- example/src/MultipleMapsScreen.tsx
- example/src/NavigationScreen.tsx
- example/src/mapsControls.tsx
- example/src/navigationControls.tsx
- package.json
- tsconfig.json
- yarn.lock
Calling the publishing workflow is broken for two reasons:
1. Improper syntax for calling the reusable workflow from release-please
2. Incorrect package name (missing `@googlemaps/`) in package.json causes mismatch in token used for npm publish action.
> chore: fix publishing workflows

- .github/workflows/ci.yml
- .gitignore
- example/README.md
- example/ios/SampleApp.xcodeproj/project.pbxproj
- example/ios/SampleApp/AppDelegate.mm
- example/ios/SampleApp/Info.plist
- example/ios/SampleApp/Keys.plist.sample
This PR moves API keys to a separate Keys.plist file for SampleApp, which is added to .gitignore. Developers should copy Keys.plist.sample as Keys.plist and update their API keys accordingly. This change helps prevent accidental commits of sensitive API keys.
> chore: gitignore active api keys for iOS SampleApp

- ios/react-native-navigation-sdk/NavViewController.m
Setting navigation view colors only works if the view has an active navigation session running. This PR modifies how map styling is controlled in the native iOS code. The styling data is now stored and applied to the navigation view after the navigation session is attached.
Fixes #246
> fix: apply styling options for iOS navigation view

- android/src/main/java/com/google/android/react/navsdk/NavViewFragment.java
Fixes #252
This PR addresses the issue where the `EventDispatcher` on Android implementation could potentially receive null data from the `NavViewEvent` `getEventData()` method, leading to crashes in specific cases (such as during the `onMapReady` event).
**Changes:**
Updated getEventData() in NavViewEvent to return an empty WritableMap when eventData is null.
> fix: ensure EventDispatcher always receives non-null data from NavViewEvent

- README.md
- android/src/main/java/com/google/android/react/navsdk/CustomTypes.java
- android/src/main/java/com/google/android/react/navsdk/EnumTranslationUtil.java
- android/src/main/java/com/google/android/react/navsdk/IMapViewFragment.java
- android/src/main/java/com/google/android/react/navsdk/INavViewFragment.java
- android/src/main/java/com/google/android/react/navsdk/IViewFragment.java
- android/src/main/java/com/google/android/react/navsdk/MapViewFragment.java
- android/src/main/java/com/google/android/react/navsdk/NavViewFragment.java
- android/src/main/java/com/google/android/react/navsdk/NavViewManager.java
- example/src/MultipleMapsScreen.tsx
- ios/react-native-navigation-sdk/CustomTypes.h
- ios/react-native-navigation-sdk/NavView.h
- ios/react-native-navigation-sdk/NavView.m
- ios/react-native-navigation-sdk/NavViewController.h
- ios/react-native-navigation-sdk/NavViewController.m
- ios/react-native-navigation-sdk/RCTNavViewManager.m
- src/maps/mapView/index.ts
- src/maps/mapView/mapView.tsx
- src/maps/mapView/types.ts
- src/maps/types.ts
- src/navigation/navigationView/navigationView.tsx
- src/shared/viewManager.ts
Resolves #254
Resolves #104
Fixes #234
- Separate MapView component has been implemented, allowing the classic map to be displayed without any effects from an ongoing or initialized navigation session.
- If map without navigation is used
- On Android a new fragment type `SupportMapFragment` is created instead of `SupportNavigationFragment`.
- On iOS the same view will be used, but the navigation session will not be attached to the map
- Fixed map zooming on iOS. Previously it always zoomed into/out of user's location.
>
> feat: map view without navigation

- README.md
chore: Update README.md in preparation for A-la-carte GA
> chore: Update README.md in preparation for A-la-carte GA

- .github/workflows/publish.yml
- README.md
- package.json
The publish workflow is failling auth; this attempts to fix it by using a per-package registry URL.
> chore: revert b182d14 and fix registry url

- ios/react-native-navigation-sdk/NavModule.m
Fixes #273
Removes min thresholds preventing onRemainingTimeOrDistanceChanged from triggering on iOS.
> fix: enable remaining time distance listener on ios

- .github/blunderbuss.yml
chore: Remove Caio/arturo from assign_issues list in blunderbuss
> chore: Remove Caio/arturo from assign_issues list in blunderbuss

- src/navigation/navigation/types.ts
Marked onTrafficUpdated callback listener as Android-only in the method documentation.
Fixes #287
> docs: document onTrafficUpdated listener as Android only

- example/README.md
Fixes #275
Example app documentation was missing information how packade dependencies should be installed for example app as it is yarn workspace project. This PR improves documentation for example app.
> docs: improve example app documentation

- android/src/main/java/com/google/android/react/navsdk/EnumTranslationUtil.java
- android/src/main/java/com/google/android/react/navsdk/NavModule.java
- example/src/App.tsx
- src/navigation/navigation/NavigationProvider.tsx
- src/navigation/navigation/types.ts
- src/navigation/navigation/useNavigationController.ts
Fixes #34 
Introduces a new property `taskRemovedBehavior` to NavigationProvider that can be used to tell Android sdk to close navigation on application exit or to keep it running:
```tsx
<NavigationProvider
termsAndConditionsDialogOptions={termsAndConditionsDialogOptions}
taskRemovedBehavior={TaskRemovedBehavior.CONTINUE_SERVICE}
>
```
> feat: support navigation disposal on app exit on android

- android/src/main/java/com/google/android/react/navsdk/NavModule.java
- android/src/main/java/com/google/android/react/navsdk/Package.java
- src/shared/useModuleListeners.ts
Fixes #272
- Initialized navigation listeners on NavigationProvider mount to avoid cases where the native layer sends messages without corresponding listener mappings.
- Keep navigation listeners registered even when NavigationProvider is disposed.
- Make Android navigation event handling more reliable by re-registering handlers on app lifecycle events; keeping them up to date with react context all the time.
> fix: handle navigation listeners on NavigationProvider mount and unmount

- android/src/main/java/com/google/android/react/navsdk/MapViewFragment.java
- android/src/main/java/com/google/android/react/navsdk/NavViewFragment.java
- example/src/App.tsx
- example/src/screens/NavigationScreen.tsx
Fixes #321
- Resolved issues with `onMarkerClick` and `onMarkerInfoWindowTapped` events on the Android platform.
- Updated the example app to allow triggering the `onMarkerInfoWindowTapped` event for testing.
> fix: onMarkerClick and onMarkerInfoWindowTapped on Android

- .github/workflows/ci.yml
Extend the timeout for the ios-build job to 45 minutes, as the previous 30-minute limit was insufficient for some builds.
> ci: increase ios-build timeout to 45 minutes

- android/src/main/java/com/google/android/react/navsdk/Command.java
Set zoom gestures command was not properly implemented on Android. This PR fixes it.
> fix: fix android set zoom gestures function

- example/src/controls/navigationControls.tsx
- example/src/styles.ts
Improves usability of the example app a bit by improving target location handling
> chore: small logic improvements to example app

- README.md
GMSServices won't work if we don't import GoogleMaps.h
> chore(readme): add GoogleMaps.h import in the readme file, required for GMS to work. 

- android/src/main/java/com/google/android/react/navsdk/Command.java
- android/src/main/java/com/google/android/react/navsdk/MapViewController.java
- android/src/main/java/com/google/android/react/navsdk/NavAutoModule.java
- android/src/main/java/com/google/android/react/navsdk/NavViewManager.java
- example/src/controls/mapsControls.tsx
- example/src/styles.ts
- ios/react-native-navigation-sdk/NavAutoModule.m
- ios/react-native-navigation-sdk/NavViewController.h
- ios/react-native-navigation-sdk/NavViewController.m
- ios/react-native-navigation-sdk/RCTNavViewManager.m
- src/auto/useNavigationAuto.ts
- src/maps/mapView/mapViewController.ts
- src/maps/mapView/types.ts
Fixes #292 
This PR adds map padding support to both regular map view as well as Android auto/Carplay map views.
> feat: add map padding

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/support_request.md
Fixes support path in issue templates
> chore: fix support path in issue templates

- android/build.gradle
- example/android/app/build.gradle
Updates navigation sdk for Android to version 6.1.0.
[Contributor Guide]: https://github.com/googlemaps/react-native-navigation-sdk/blob/main/CONTRIBUTING.md
[CLA]: https://cla.developers.google.com/
> chore: update Navigation SDK for Android to version 6.1.0

- android/src/main/java/com/google/android/react/navsdk/Command.java
- android/src/main/java/com/google/android/react/navsdk/EnumTranslationUtil.java
- android/src/main/java/com/google/android/react/navsdk/NavModule.java
- android/src/main/java/com/google/android/react/navsdk/NavViewFragment.java
- android/src/main/java/com/google/android/react/navsdk/NavViewLayout.java
- android/src/main/java/com/google/android/react/navsdk/NavViewManager.java
- android/src/main/java/com/google/android/react/navsdk/NavViewModule.java
- example/package.json
- example/src/screens/MultipleMapsScreen.tsx
- example/src/screens/NavigationScreen.tsx
- example/src/styles.ts
- ios/react-native-navigation-sdk/NavModule.m
- ios/react-native-navigation-sdk/NavView.h
- ios/react-native-navigation-sdk/NavView.m
- ios/react-native-navigation-sdk/NavViewController.h
- ios/react-native-navigation-sdk/NavViewModule.h
- ios/react-native-navigation-sdk/NavViewModule.m
- ios/react-native-navigation-sdk/RCTNavViewManager.m
- scripts/format.sh
- src/maps/mapView/mapView.tsx
- src/maps/mapView/types.ts
- src/navigation/navigationView/navigationView.tsx
- src/shared/viewManager.ts
- yarn.lock
- Improves how views are created by dropping createFragment command call
- Improves how views are disposed and fragments removed on Android platform
- Improves null checking for both platforms
Fixes #309
[Contributor Guide]: https://github.com/googlemaps/react-native-navigation-sdk/blob/main/CONTRIBUTING.md
[CLA]: https://cla.developers.google.com/
> fix: view lifecycle issue

- CHANGELOG.md
- android/build.gradle
- android/src/main/java/com/google/android/react/navsdk/NavModule.java
- android/src/main/java/com/google/android/react/navsdk/ObjectTranslationUtil.java
- example/android/app/build.gradle
- example/src/screens/MultipleMapsScreen.tsx
- example/src/screens/NavigationScreen.tsx
- src/navigation/navigation/types.ts
- src/navigation/shared.ts
- src/navigation/types.ts
***Breaking change:***
- Upgrades Google Maps Navigation SDK for Android to version 7.0.0
- Adds new enum value RouteStatus.DUPLICATE_WAYPOINTS_ERROR
- Updates targetSdkVersion to 36
[Contributor Guide]: https://github.com/googlemaps/react-native-navigation-sdk/blob/main/CONTRIBUTING.md
[CLA]: https://cla.developers.google.com/
> feat!: upgrade Android SDK to 7.0.0
